### ISSUE TITLE
Handle pre-declared opaque structure types

### ISSUE THREAD

**Issue by nilslice** [rigetti/qcs-sdk-qir#15]
e.g. 
```ll
%ExecutableCache = type opaque
%ExecutableCache.2 = type opaque ; re-declared & used
%Array = type opaque
%Qubit = type opaque
%Result = type opaque
%String = type opaque
%Executable = type opaque
%ExecutionResult = type opaque
%Executable.1 = type opaque ; re-declared & used
%ExecutionResult.0 = type opaque ; re-declared & used
```

`qcs-sdk-qir` should probably look to see if any of these have been declared prior to its `transform` step. If known type identifier is encountered, it seems like it should be an error, but currently it is accepted and a new declaration is made.

**Comment by kalzoo** [comment]
Makes sense from a hygiene point of view, and I imagine that this prevents compilation to binary from working as well.
