### ISSUE TITLE
Support Proposed Base Profile / Unitary QIR

### ISSUE THREAD

**Issue by kalzoo** [rigetti/qcs-sdk-qir#8]
In discussion in a QIR working group is the "base profile," the lowest common denominator for all QIR programs, or the minimal useful program.

Proposed by a partner is the following definition:

- A single function which is also the entrypoint
- That function's body contains a single basic block, which itself contains a quantum program, composed of only quantum intrinsics.
- Its terminator - because a terminator is required - is a `ret void` instruction.
- `double` parameters are supported, but those parametric values must be arguments to the function

Any deviation from this pattern should result in an error. Shot counts will be provided to the runtime as metadata rather than directly within the program.

The output/target, in this case, should be selectable; either Quil program text or LLVM IR.

Worth consideration:

- user selection of the profile, so as to choose whether to support the shot-count pattern or this simpler pattern
- reusability and composability of patterns

**Comment by nilslice** [comment]
Some public info on Base Profile: 
https://github.com/microsoft/qsharp-language/blob/ageller/profile/Specifications/QIR/Base-Profile.md

**Comment by nilslice** [comment]
Done | Operation | LLVM Function Declaration | Description
-- | -- | -- | --
:heavy_check_mark: | CCX, CCNOT, Toffoli | `@__quantum__qis__toffoli_body (%Qubit*, %Qubit*, %Qubit*)` | Toffoli or doubly-controlled X
:heavy_check_mark: |CX, CNOT | `@__quantum__qis__cnot_body (%Qubit*, %Qubit*)` | CNOT or singly-controlled X
:heavy_check_mark: | CZ | `@__quantum__qis__cz_body (%Qubit*, %Qubit*)` | Singly-controlled Z
:heavy_check_mark: | H | `@__quantum__qis__h_body (%Qubit*)` | Hadamard
:heavy_check_mark: | MZ or MEASURE | `@__quantum__qis__mz_body (%Qubit*, i32)` | Measure a qubit along the the Pauli Z axis
:heavy_check_mark: | RESET | `@__quantum__qis__reset_body (%Qubit*)` | Prepare a qubit in the \|0⟩ state
:heavy_check_mark: | RX | `@__quantum__qis__rx_body (double, %Qubit*)` | Rotate a qubit around the X axis
:heavy_check_mark: | RY | `@__quantum__qis__ry_body (double, %Qubit*)` | Rotate a qubit around the Y axis
:heavy_check_mark: | RZ | `@__quantum__qis__rz_body (double, %Qubit*)` | Rotate a qubit around the  Z axis
:heavy_check_mark: | S | `@__quantum__qis__s_body (%Qubit*)` | S (phase pi/2 gate)
:heavy_check_mark: | DAGGER S | `@__quantum__qis__s_adj (%Qubit*)` | The adjoint of S
:heavy_check_mark: | T | `@__quantum__qis__t_body (%Qubit*)` | T (phase pi/4 gate)
:heavy_check_mark: | DAGGER T | `@__quantum__qis__t_adj (%Qubit*)` | The adjoint of T
:heavy_check_mark: | X | `@__quantum__qis__x_body (%Qubit*)` | Pauli X
:heavy_check_mark: | Y | `@__quantum__qis__y_body (%Qubit*)` | Pauli Y
:heavy_check_mark: | Z | `@__quantum__qis__z_body (%Qubit*)` | Pauli Z
:heavy_check_mark: | SWAP | `@__quantum__qis__swap_body (%Qubit*, %Qubit*)` | SWAP q1 and q2

**Comment by nilslice** [comment]
Checklist:
- [ ] Handle `EntryPoint` (#14)
- [x] Implement gate set
- [x] Implement runtime record functions
- [ ] Validate only `double` params used in gate instructions
  - [x] implicitly by LLVM type system
  - [ ] explicitly by pattern code (may not be necessary)
- [ ] `--format` flag, options: `unitary` or `shot-count` 
- [ ] works with both `transform` (output: LLVM IR) and `transpile-to-quil` (output: Quil + recorded output mapping, no shot count)

**Comment by nilslice** [comment]
Closed in #30.
